In [1]:
#Matrix multiplication and transpose

import numpy as np
arr1=np.array([2,4,6,8,1,3,5,7,9]).reshape(3,3)
print("Matrix 1: \n",arr1,"\n")
arr2=np.array([1,3,5,7,9,2,4,6,8]).reshape(3,3)
print("Matrix 2: \n",arr2,"\n")
arr3=np.dot(arr1,arr2)
print("After Matrix multiplication: \n",arr3,"\n")

trans=np.transpose(arr3)
print("Transpose of Matrix: \n",trans)

Matrix 1: 
 [[2 4 6]
 [8 1 3]
 [5 7 9]] 

Matrix 2: 
 [[1 3 5]
 [7 9 2]
 [4 6 8]] 

After Matrix multiplication: 
 [[ 54  78  66]
 [ 27  51  66]
 [ 90 132 111]] 

Transpose of Matrix: 
 [[ 54  27  90]
 [ 78  51 132]
 [ 66  66 111]]
