In [1]:
#svd

import numpy as np
from scipy.linalg import svd

arr=np.array([2,4,6,8,1,3,5,7,9]).reshape(3,3)
a,b,c=svd(arr)

print("Decomposed using svd : \n")
print(a)
print("\n",b)
print("\n",c)

print("\n After reconstructed : \n")

r=(a @ np.diag(b) @c)
new_array=r.astype("i")
print("\n",new_array)

Decomposed using svd : 

[[-0.45560124  0.33742468 -0.82375487]
 [-0.42819003 -0.89435856 -0.12952244]
 [-0.78043629  0.29371304  0.55195276]]

 [15.78948981  5.94653205  0.57512454]

 [[-0.52179673 -0.48853061 -0.69933255]
 [-0.84275236  0.42231866  0.33378947]
 [ 0.13227481  0.76353441 -0.63207482]]

 After reconstructed : 


 [[2 3 5]
 [7 1 2]
 [5 6 8]]
